import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({ name }) {
  return (
    <div className={styles.container}>
      <Head> {/** Insere os elementos na tag <head> nativa do html */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Nome: {name}
        </h1>
        <h2>
        </h2>
      </main>
    </div>
  )
}

/**
 * @description getStaticProps -> Renderiza o componente (tela) acima, no momento do build.
 */
export async function getStaticProps() {
  return {
    props: {
      name: "Guilherme"
    }
  }
}
